main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('records/', views.records, name='records'),
    path('myrecords/', views.my_records, name='my_records'),
    path('records/<int:record_id>/', views.records_detail, name='detail'),
    path('records/add/', views.RecordCreate.as_view(), name='records_add'),
    path('records/<int:pk>/update/', views.RecordUpdate.as_view(), name='records_update'),
    path('records/<int:pk>/delete/', views.RecordDelete.as_view(), name='records_delete'),
    path('collections/', views.collections, name='collections'),
    # path('collections/', views.CollectionList.as_view(), name='collections'),
    path('collections/<int:pk>/', views.CollectionDetail.as_view(), name='collections_detail'),
    path('accounts/signup', views.signup, name='signup'),
    path('records/<int:record_id>/add_photo', views.add_photo, name='add_photo'),
    path('records/<int:collection_id>/assoc_record/<int:record_id>/', views.assoc_record, name='assoc_record'),
    path('records/<int:record_id>/assoc_record/<int:collection_id>/', views.assoc_record, name='assoc_record'),
]

vinylog/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

main_app/models.py
from pyexpat import model
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
# from .models import Photo

# Create your models here.
class Record(models.Model):
    artist = models.CharField(max_length=100)
    title = models.CharField(max_length=200)
    release_date = models.DateField()
    genre = models.CharField(max_length=100)
    description = models.CharField(max_length=500)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # photo = models.ForeignKey(Photo, on_delete=models.CASCADE)

    def __str__(self):
        return self.artist + " - " + self.title

    def get_absolute_url(self):
        return reverse('detail', kwargs={'record_id': self.id})

    class Meta:
        ordering = ['-release_date']

class Collection(models.Model):
    date_added = models.DateField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    record = models.ManyToManyField(Record)
    # notes = models.CharField(max_length=200)
    # condition = models.CharField(max_length=100)

    class Meta:
        ordering = ['-date_added'] 

    def __str__(self):
        return f"{self.user}'s collection"
    
    def get_absolute_url(self):
        return reverse('collections_detail', kwargs={'pk': self.id})

class Photo(models.Model):
    url = models.CharField(max_length=200)
    record = models.ForeignKey(Record, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for record_id: {self.record_id} @{self.url}"

main_app/views.py
import uuid
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.shortcuts import render
from .models import Record, Collection, Photo
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView
from django.views.generic.detail import DetailView
import uuid
import boto3

S3_BASE_URL = 'https://s3.us-east-1.amazonaws.com/'
BUCKET = 'vinylog'

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def records(request):
    records = Record.objects.all()
    photos = Photo.objects.all()
    return render(request, 'records/index.html', { 'records': records, 'photos': photos })
    

def my_records(request):
  records = Record.objects.filter(user=request.user)
  return render(request, 'records/myrecords.html', { 'records': records })

# # Work version without collection integration
# def records_detail(request, record_id):
#     record = Record.objects.get(id=record_id)
#     collection = Collection.objects.filter()
#     return render(request, 'records/detail.html', { 'record': record, 'collection': collection })

# Collection integration
def records_detail(request, record_id):
    record = Record.objects.get(id=record_id)
    collections = Collection.objects.all()
    return render(request, 'records/detail.html', { 'record': record, 'collections': collections})

class RecordCreate(LoginRequiredMixin, CreateView):
    model = Record
    fields = ['artist', 'title', 'release_date', 'genre', 'description']
    succes_url = '/records/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class RecordUpdate(LoginRequiredMixin, UpdateView):
    model = Record
    fields = ['description']

class RecordDelete(LoginRequiredMixin, DeleteView):
    model = Record
    success_url = '/records/'

def collections(request):
    collections = Collection.objects.all()
    return render(request, 'collections/index.html', { 'collections': collections })


def assoc_record(request, collection_id, record_id):
    Collection.objects.get(id=collection_id).records.add(record_id)
    return redirect('detail', record_id=record_id)

# def collections_detail(request, collection_id):
#     collection = Collection.objects.get(collection_id)
#     return render(request, 'collections/detail.html', { 'collection': collection})

# class CollectionList (ListView):
#     model = Collection
#     template_name = 'collections/index.html'

class CollectionDetail (DetailView):
    model = Collection
    template_name = 'collections/detail.html'


@login_required
def add_photo(request, record_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            photo = Photo(url=url, record_id=record_id)
            photo.save()
        except Exception as error:
            print('An error occurred uploading file to S3', error)
            return redirect('detail', record_id=record_id)
    return redirect('detail', record_id=record_id)

def signup(request):
    error_messages = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        try:
            user = form.save()
            login(request, user)
            return redirect('records')
        except:
            error_messages = form.errors
    form = UserCreationForm()
    context = {'form': form, 'error_messages': error_messages}
    return render(request, 'registration/signup.html', context)

main_app/templates/about.html
{% extends 'base.html' %} {% block content %}
<h1 class="no-card">About <span class="brand-logo no-card">vinyLog</span></h1>
<hr />
<h4 class="no-card">
  vinyLog was designed to help users keep track of their record collections.
</h4>
<br />
{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>vinyLog</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />

    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.css' %}"
    />
    <link
      href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Acme&family=Amatic+SC&family=Berkshire+Swash&family=Cookie&family=Courgette&family=Gloria+Hallelujah&family=Great+Vibes&family=Kaushan+Script&family=Lobster&family=Permanent+Marker&family=Play&family=Press+Start+2P&family=Sacramento&family=Satisfy&family=The+Nautigal&display=swap"
      rel="stylesheet"
    />
    <style>
      .cover {
        border: 1px solid black;
      }
    </style>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>
  <body>
    <header class="navbar-fixed">
      <nav class="grey">
        <div class="nav-wrapper">
          <ul>
            <li>
              <a href="/" class="left brand-logo"> vinyLog</a>
            </li>
          </ul>
          <ul class="right">
            {% if user.is_authenticated %}
            <ul id="dropdown1" class="dropdown-content">
              <li>
                <a class="link" href="{% url 'records' %}">View All Records</a>
              </li>
              <li>
                <a class="link" href="{% url 'my_records' %}"
                  >Your Contributions</a
                >
              </li>
              <li>
                <a class="link" href="{% url 'records_add' %}">Add a Record</a>
              </li>
            </ul>
            <li>
              <a class="dropdown-trigger" href="#!" data-target="dropdown1"
                >Records<i class="material-icons right">arrow_drop_down</i></a
              >
            </li>
            <li><a href="{% url 'collections' %}">View All Collections</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
            <li class="logout">
              <a href="{% url 'logout' %}">Logout ({{ user }})</a>
            </li>
            {% else %}
            <li><a href="{% url 'about' %}">About</a></li>
            <li class="signup">
              <a class="signup" href="{% url 'signup' %}">Sign Up</a>
            </li>
            <li class="login">
              <a href="{% url 'login' %}">Login</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer">
      <div class="right">All Rights Reserved, © 2022 VinyLog</div>
    </footer>
  </body>
</html>
<script>
  $(document).ready(function () {
    $(".dropdown-trigger").dropdown()
  })
</script>

main_app/templates/collections/detail.html
{% extends 'base.html' %} {% block content %}

<h1 class="no-card">{{ collection.user }}'s Collection</h1>
<p>{{ collection.records.all }}</p>
{% for record in collection.record.all %}

<div class="card index-card">
  <a href="{% url 'detail' record.id %}">
    <div class="card-content">
      <span class="card-title"
        ><strong>{{ record.artist }}</strong> -
        <em>{{ record.title }}</em></span
      >
      <p>Release Date: {{ record.release_date }}</p>
    </div>
  </a>
</div>

{% endfor %} {% endblock %}

main_app/templates/collections/index.html
{% extends 'base.html' %} {% block content %}

<h1 class="no-card">Collections List</h1>

{% for collection in collections %}

<div class="card index-card">
  <a href="{% url 'collections_detail' collection.id %}">
    <div class="card-content">
      <span class="card-title"
        ><strong>{{ collection.user }}</strong>'s Collection</span
      >
      <p></p>
      <p></p>
    </div>
  </a>
</div>

{% endfor %} {% endblock %}

main_app/templates/home.html
{% extends 'base.html' %} {%block content %}

<h1 class="no-card">This is the Home Page!</h1>

{% endblock %}

main_app/templates/main_app/record_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1 class="no-card">Delete Record</h1>

<h4 class="no-card">
  Are you sure you want to delete
  <strong><span class="teal-text">{{ object.title }}</span></strong
  >?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn red" />
  <a href="{% url 'detail' record.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/record_form.html
{% extends 'base.html' %} {% block content %} {% if object %}
<h1 class="no-card">Edit <span class="teal-text">{{ object.title }}</span></h1>
{% else %}
<h1 class="no-card">Add Record</h1>
{% endif %}
<form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <br />
  <input type="submit" value="Submit!" class="btn green" />
</form>
<script>
  let dateEl = document.getElementById("id_release_date")
  M.Datepicker.init(dateEl, {
    format: "yyyy-mm-dd",
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true,
  })
  console.log(dateEl)
</script>
{% endblock %}

main_app/templates/records/detail.html
{% extends 'base.html' %} {% block content %}

<h1 class="no-card">Record Details</h1>

<div class="row">
  <div class="col s5">
    {% for photo in record.photo_set.all %}
    <img class="responsive-img card-panel" class="cover" src="{{ photo.url }}" />
    {% empty %}
    <div class="card-panel teal-text center-align">Cover Art Missing</div>
    <form
    action="{% url 'add_photo' record.id %}"
    enctype="multipart/form-data"
    method="POST"
    class="card-panel"
    >
    {% csrf_token %}
    <input type="file" name="photo-file" />
    <br /><br />
    <input type="submit" class="btn green" value="Upload Photo" />
  </form>
  {% endfor %}
  </div>
  <div class="col s7">
    <div class="card">
      <div class="card-content">
        <span class="card-title"><strong>{{ record.artist }}</strong> - <em>{{ record.title}}</em> ({{ record.release_date.year }})</span>
        <p>Release Date: {{ record.release_date }}</p>
      
        <p>({{ record.genre }})</p>
      </br>
        <p>{{ record.description }}</p>
      </br>
      <p>Added by: {{ record.user }}</p>
      </div>
      {% if request.user == record.user %}
      <div class="card-action">
        <a class="btn yellow" href="{% url 'records_update' record.id %}">Edit</a>
        <a class='btn red' href="{% url 'records_delete' record.id %}">Delete</a>
      </div>
      {% endif %}
    </div>
  </div>
</div>
<div class="card-action"></div>
<!-- <p>{{ collections.all }}</p>
{% for collection in collections %}

{% for item in collection.record.all %}

{% if item == record %}
{% if collection.user == request.user %}
<h5 class="no-card">{{ record.title }} is in your collection</h5>
{% else %}
<h5 class="no-card">{{ record.title }} is not in your collection</h5>
{% endif %}
{% endif %}
{% endfor %}
{% endfor %} -->
<!-- <p>Add to your collection:</p> -->

<hr />
<p>{{ collections.all.records }}</p>
<h5 class="no-card"><em>{{ record.title }} </em> is in the following user's collections:</h5>
{% for collection in collections %}
{% for item in collection.record.all %}
{% if item == record %}
<div class="card index-card">
  <a href="{% url 'collections_detail' collection.id %}">
    <div class="card-content">
      <span class="card-title">{{ collection.user }}'s Collection</span>
      <p></p>
      <p></p>
    </div>
  </a>
</div>
{% endif %}
{% endfor %}
{% endfor %}
<!-- <h5 class="no-card"><s>{{ record.title }} is not in anyone's collection</s></h5> -->
<div class="row">
  <div class="col s12">
    <p class="no-card">{% if collection.records.count %}</p>
    <h5 class="no-card"><em>{{ record.title }}</em> is in the following user's Collections:</h5>
    {% for collection in record.collections.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title"> A <span>{{ collection.user }}</span> </span>
      </div>
    </div>
    {% endfor %} {% else %}
    
    {% endif %}
  </div>
  
  <!-- Available toys will come after this line -->
</div>

{% endblock %}

main_app/templates/records/index.html
{% extends 'base.html' %} {% block content %}

<h1 class="no-card">All Records</h1>

<!-- {% for photo in photos %}
<img src="{{ photo.url }}" />
{% endfor %}  -->
{% for record in records %}
<div class="card index-card">
  <a href="{% url 'detail' record.id %}">
    <div class="card-content">
      <span class="card-title">
        <strong>{{ record.artist }}</strong> -
        <em>{{ record.title }}</em> ({{record.release_date.year}})
      </span>
      <p>Release Date: {{ record.release_date }}</p>
    </div>
  </a>
</div>
{% endfor %} {% endblock %}

main_app/templates/records/myrecords.html
{% extends 'base.html' %} {% block content %}

<h1 class="no-card">Records You've Added</h1>

<!-- {% for photo in photos %}
<img src="{{ photo.url }}" />
{% endfor %}  -->
{% for record in records %}
<div class="card index-card">
  <a href="{% url 'detail' record.id %}">
    <div class="card-content">
      <span class="card-title">
        <strong>{{ record.artist }}</strong> - <em>{{ record.title }}</em>
      </span>
      <p>Release Date: {{ record.release_date }}</p>
    </div>
  </a>
</div>
{% endfor %} {% endblock %}